// Code generated by pigeon; DO NOT EDIT.

// Package parser provides SQL parsing for a subset of SQL
// that maps to the ISBD DBMS OpenAPI interface.
//
// This file is the source of truth for the SQL grammar.
// To regenerate the parser, run:
//   go generate ./...
//
// Grammar supports:
//   - SELECT with column expressions
//   - FROM clause (optional, table name is parsed but not stored)
//   - WHERE clause with boolean expressions
//   - ORDER BY clause (by column index, ASC/DESC)
//   - LIMIT clause
//   - Arithmetic operators: +, -, *, /
//   - Comparison operators: =, <>, !=, <, <=, >, >=
//   - Logical operators: AND, OR, NOT
//   - Functions: STRLEN, CONCAT, UPPER, LOWER
//   - Literals: integers, strings, TRUE, FALSE
//   - Column references: column or table.column

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Query",
			pos:  position{line: 33, col: 1, offset: 1010},
			expr: &actionExpr{
				pos: position{line: 33, col: 10, offset: 1019},
				run: (*parser).callonQuery1,
				expr: &seqExpr{
					pos: position{line: 33, col: 10, offset: 1019},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 33, col: 10, offset: 1019},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 33, col: 12, offset: 1021},
							val:        "select",
							ignoreCase: true,
							want:       "\"SELECT\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 22, offset: 1031},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 33, col: 24, offset: 1033},
							label: "columns",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 32, offset: 1041},
								name: "ColumnList",
							},
						},
						&labeledExpr{
							pos:   position{line: 33, col: 43, offset: 1052},
							label: "from",
							expr: &zeroOrOneExpr{
								pos: position{line: 33, col: 48, offset: 1057},
								expr: &ruleRefExpr{
									pos:  position{line: 33, col: 48, offset: 1057},
									name: "FromClause",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 33, col: 60, offset: 1069},
							label: "where",
							expr: &zeroOrOneExpr{
								pos: position{line: 33, col: 66, offset: 1075},
								expr: &ruleRefExpr{
									pos:  position{line: 33, col: 66, offset: 1075},
									name: "WhereClause",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 34, col: 10, offset: 1098},
							label: "orderBy",
							expr: &zeroOrOneExpr{
								pos: position{line: 34, col: 18, offset: 1106},
								expr: &ruleRefExpr{
									pos:  position{line: 34, col: 18, offset: 1106},
									name: "OrderByClause",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 34, col: 33, offset: 1121},
							label: "limit",
							expr: &zeroOrOneExpr{
								pos: position{line: 34, col: 39, offset: 1127},
								expr: &ruleRefExpr{
									pos:  position{line: 34, col: 39, offset: 1127},
									name: "LimitClause",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 52, offset: 1140},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 34, col: 54, offset: 1142},
							expr: &litMatcher{
								pos:        position{line: 34, col: 54, offset: 1142},
								val:        ";",
								ignoreCase: false,
								want:       "\";\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 59, offset: 1147},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 61, offset: 1149},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "ColumnList",
			pos:  position{line: 42, col: 1, offset: 1390},
			expr: &actionExpr{
				pos: position{line: 42, col: 15, offset: 1404},
				run: (*parser).callonColumnList1,
				expr: &seqExpr{
					pos: position{line: 42, col: 15, offset: 1404},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 42, col: 15, offset: 1404},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 21, offset: 1410},
								name: "Expr",
							},
						},
						&labeledExpr{
							pos:   position{line: 42, col: 26, offset: 1415},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 42, col: 31, offset: 1420},
								expr: &actionExpr{
									pos: position{line: 42, col: 33, offset: 1422},
									run: (*parser).callonColumnList7,
									expr: &seqExpr{
										pos: position{line: 42, col: 33, offset: 1422},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 42, col: 33, offset: 1422},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 42, col: 35, offset: 1424},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 42, col: 39, offset: 1428},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 42, col: 41, offset: 1430},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 42, col: 43, offset: 1432},
													name: "Expr",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FromClause",
			pos:  position{line: 46, col: 1, offset: 1508},
			expr: &actionExpr{
				pos: position{line: 46, col: 15, offset: 1522},
				run: (*parser).callonFromClause1,
				expr: &seqExpr{
					pos: position{line: 46, col: 15, offset: 1522},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 46, col: 15, offset: 1522},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 46, col: 17, offset: 1524},
							val:        "from",
							ignoreCase: true,
							want:       "\"FROM\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 25, offset: 1532},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 27, offset: 1534},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 33, offset: 1540},
								name: "Identifier",
							},
						},
						&labeledExpr{
							pos:   position{line: 46, col: 44, offset: 1551},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 46, col: 49, offset: 1556},
								expr: &actionExpr{
									pos: position{line: 46, col: 51, offset: 1558},
									run: (*parser).callonFromClause10,
									expr: &seqExpr{
										pos: position{line: 46, col: 51, offset: 1558},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 46, col: 51, offset: 1558},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 46, col: 53, offset: 1560},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 46, col: 57, offset: 1564},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 46, col: 59, offset: 1566},
												label: "name",
												expr: &ruleRefExpr{
													pos:  position{line: 46, col: 64, offset: 1571},
													name: "Identifier",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "WhereClause",
			pos:  position{line: 50, col: 1, offset: 1656},
			expr: &actionExpr{
				pos: position{line: 50, col: 16, offset: 1671},
				run: (*parser).callonWhereClause1,
				expr: &seqExpr{
					pos: position{line: 50, col: 16, offset: 1671},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 50, col: 16, offset: 1671},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 50, col: 18, offset: 1673},
							val:        "where",
							ignoreCase: true,
							want:       "\"WHERE\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 27, offset: 1682},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 50, col: 29, offset: 1684},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 34, offset: 1689},
								name: "Expr",
							},
						},
					},
				},
			},
		},
		{
			name: "OrderByClause",
			pos:  position{line: 54, col: 1, offset: 1720},
			expr: &actionExpr{
				pos: position{line: 54, col: 18, offset: 1737},
				run: (*parser).callonOrderByClause1,
				expr: &seqExpr{
					pos: position{line: 54, col: 18, offset: 1737},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 54, col: 18, offset: 1737},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 54, col: 20, offset: 1739},
							val:        "order",
							ignoreCase: true,
							want:       "\"ORDER\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 29, offset: 1748},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 54, col: 31, offset: 1750},
							val:        "by",
							ignoreCase: true,
							want:       "\"BY\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 37, offset: 1756},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 54, col: 39, offset: 1758},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 45, offset: 1764},
								name: "OrderByItem",
							},
						},
						&labeledExpr{
							pos:   position{line: 54, col: 57, offset: 1776},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 54, col: 62, offset: 1781},
								expr: &actionExpr{
									pos: position{line: 54, col: 64, offset: 1783},
									run: (*parser).callonOrderByClause12,
									expr: &seqExpr{
										pos: position{line: 54, col: 64, offset: 1783},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 54, col: 64, offset: 1783},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 54, col: 66, offset: 1785},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 54, col: 70, offset: 1789},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 54, col: 72, offset: 1791},
												label: "o",
												expr: &ruleRefExpr{
													pos:  position{line: 54, col: 74, offset: 1793},
													name: "OrderByItem",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OrderByItem",
			pos:  position{line: 58, col: 1, offset: 1877},
			expr: &actionExpr{
				pos: position{line: 58, col: 16, offset: 1892},
				run: (*parser).callonOrderByItem1,
				expr: &seqExpr{
					pos: position{line: 58, col: 16, offset: 1892},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 58, col: 16, offset: 1892},
							label: "idx",
							expr: &ruleRefExpr{
								pos:  position{line: 58, col: 20, offset: 1896},
								name: "Integer",
							},
						},
						&labeledExpr{
							pos:   position{line: 58, col: 28, offset: 1904},
							label: "dir",
							expr: &zeroOrOneExpr{
								pos: position{line: 58, col: 32, offset: 1908},
								expr: &actionExpr{
									pos: position{line: 58, col: 34, offset: 1910},
									run: (*parser).callonOrderByItem7,
									expr: &seqExpr{
										pos: position{line: 58, col: 34, offset: 1910},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 58, col: 34, offset: 1910},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 58, col: 36, offset: 1912},
												label: "d",
												expr: &choiceExpr{
													pos: position{line: 58, col: 39, offset: 1915},
													alternatives: []any{
														&litMatcher{
															pos:        position{line: 58, col: 39, offset: 1915},
															val:        "asc",
															ignoreCase: true,
															want:       "\"ASC\"i",
														},
														&litMatcher{
															pos:        position{line: 58, col: 48, offset: 1924},
															val:        "desc",
															ignoreCase: true,
															want:       "\"DESC\"i",
														},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LimitClause",
			pos:  position{line: 62, col: 1, offset: 2015},
			expr: &actionExpr{
				pos: position{line: 62, col: 16, offset: 2030},
				run: (*parser).callonLimitClause1,
				expr: &seqExpr{
					pos: position{line: 62, col: 16, offset: 2030},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 62, col: 16, offset: 2030},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 62, col: 18, offset: 2032},
							val:        "limit",
							ignoreCase: true,
							want:       "\"LIMIT\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 62, col: 27, offset: 2041},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 62, col: 29, offset: 2043},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 62, col: 31, offset: 2045},
								name: "Integer",
							},
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 70, col: 1, offset: 2306},
			expr: &ruleRefExpr{
				pos:  position{line: 70, col: 9, offset: 2314},
				name: "OrExpr",
			},
		},
		{
			name: "OrExpr",
			pos:  position{line: 72, col: 1, offset: 2322},
			expr: &actionExpr{
				pos: position{line: 72, col: 11, offset: 2332},
				run: (*parser).callonOrExpr1,
				expr: &seqExpr{
					pos: position{line: 72, col: 11, offset: 2332},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 72, col: 11, offset: 2332},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 17, offset: 2338},
								name: "AndExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 72, col: 25, offset: 2346},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 72, col: 30, offset: 2351},
								expr: &actionExpr{
									pos: position{line: 72, col: 32, offset: 2353},
									run: (*parser).callonOrExpr7,
									expr: &seqExpr{
										pos: position{line: 72, col: 32, offset: 2353},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 72, col: 32, offset: 2353},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 72, col: 34, offset: 2355},
												val:        "or",
												ignoreCase: true,
												want:       "\"OR\"i",
											},
											&ruleRefExpr{
												pos:  position{line: 72, col: 40, offset: 2361},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 72, col: 42, offset: 2363},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 72, col: 44, offset: 2365},
													name: "AndExpr",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AndExpr",
			pos:  position{line: 76, col: 1, offset: 2451},
			expr: &actionExpr{
				pos: position{line: 76, col: 12, offset: 2462},
				run: (*parser).callonAndExpr1,
				expr: &seqExpr{
					pos: position{line: 76, col: 12, offset: 2462},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 76, col: 12, offset: 2462},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 76, col: 18, offset: 2468},
								name: "Comparison",
							},
						},
						&labeledExpr{
							pos:   position{line: 76, col: 29, offset: 2479},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 76, col: 34, offset: 2484},
								expr: &actionExpr{
									pos: position{line: 76, col: 36, offset: 2486},
									run: (*parser).callonAndExpr7,
									expr: &seqExpr{
										pos: position{line: 76, col: 36, offset: 2486},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 76, col: 36, offset: 2486},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 76, col: 38, offset: 2488},
												val:        "and",
												ignoreCase: true,
												want:       "\"AND\"i",
											},
											&ruleRefExpr{
												pos:  position{line: 76, col: 45, offset: 2495},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 76, col: 47, offset: 2497},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 76, col: 49, offset: 2499},
													name: "Comparison",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Comparison",
			pos:  position{line: 80, col: 1, offset: 2589},
			expr: &actionExpr{
				pos: position{line: 80, col: 15, offset: 2603},
				run: (*parser).callonComparison1,
				expr: &seqExpr{
					pos: position{line: 80, col: 15, offset: 2603},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 80, col: 15, offset: 2603},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 80, col: 20, offset: 2608},
								name: "Additive",
							},
						},
						&labeledExpr{
							pos:   position{line: 80, col: 29, offset: 2617},
							label: "op",
							expr: &zeroOrOneExpr{
								pos: position{line: 80, col: 32, offset: 2620},
								expr: &ruleRefExpr{
									pos:  position{line: 80, col: 32, offset: 2620},
									name: "CompOp",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 80, col: 40, offset: 2628},
							label: "right",
							expr: &zeroOrOneExpr{
								pos: position{line: 80, col: 46, offset: 2634},
								expr: &ruleRefExpr{
									pos:  position{line: 80, col: 46, offset: 2634},
									name: "Additive",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CompOp",
			pos:  position{line: 84, col: 1, offset: 2698},
			expr: &actionExpr{
				pos: position{line: 84, col: 11, offset: 2708},
				run: (*parser).callonCompOp1,
				expr: &seqExpr{
					pos: position{line: 84, col: 11, offset: 2708},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 84, col: 11, offset: 2708},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 84, col: 13, offset: 2710},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 84, col: 18, offset: 2715},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 84, col: 18, offset: 2715},
										val:        "<=",
										ignoreCase: false,
										want:       "\"<=\"",
									},
									&litMatcher{
										pos:        position{line: 84, col: 25, offset: 2722},
										val:        ">=",
										ignoreCase: false,
										want:       "\">=\"",
									},
									&litMatcher{
										pos:        position{line: 84, col: 32, offset: 2729},
										val:        "<>",
										ignoreCase: false,
										want:       "\"<>\"",
									},
									&litMatcher{
										pos:        position{line: 84, col: 39, offset: 2736},
										val:        "!=",
										ignoreCase: false,
										want:       "\"!=\"",
									},
									&litMatcher{
										pos:        position{line: 84, col: 46, offset: 2743},
										val:        "<",
										ignoreCase: false,
										want:       "\"<\"",
									},
									&litMatcher{
										pos:        position{line: 84, col: 52, offset: 2749},
										val:        ">",
										ignoreCase: false,
										want:       "\">\"",
									},
									&litMatcher{
										pos:        position{line: 84, col: 58, offset: 2755},
										val:        "=",
										ignoreCase: false,
										want:       "\"=\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 84, col: 64, offset: 2761},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Additive",
			pos:  position{line: 88, col: 1, offset: 2799},
			expr: &actionExpr{
				pos: position{line: 88, col: 13, offset: 2811},
				run: (*parser).callonAdditive1,
				expr: &seqExpr{
					pos: position{line: 88, col: 13, offset: 2811},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 88, col: 13, offset: 2811},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 88, col: 19, offset: 2817},
								name: "Multiplicative",
							},
						},
						&labeledExpr{
							pos:   position{line: 88, col: 34, offset: 2832},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 88, col: 39, offset: 2837},
								expr: &actionExpr{
									pos: position{line: 88, col: 41, offset: 2839},
									run: (*parser).callonAdditive7,
									expr: &seqExpr{
										pos: position{line: 88, col: 41, offset: 2839},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 88, col: 41, offset: 2839},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 88, col: 43, offset: 2841},
												label: "op",
												expr: &ruleRefExpr{
													pos:  position{line: 88, col: 46, offset: 2844},
													name: "AddOp",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 88, col: 52, offset: 2850},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 88, col: 54, offset: 2852},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 88, col: 56, offset: 2854},
													name: "Multiplicative",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 92, col: 1, offset: 2962},
			expr: &actionExpr{
				pos: position{line: 92, col: 10, offset: 2971},
				run: (*parser).callonAddOp1,
				expr: &labeledExpr{
					pos:   position{line: 92, col: 10, offset: 2971},
					label: "op",
					expr: &choiceExpr{
						pos: position{line: 92, col: 15, offset: 2976},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 92, col: 15, offset: 2976},
								val:        "+",
								ignoreCase: false,
								want:       "\"+\"",
							},
							&litMatcher{
								pos:        position{line: 92, col: 21, offset: 2982},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
					},
				},
			},
		},
		{
			name: "Multiplicative",
			pos:  position{line: 96, col: 1, offset: 3024},
			expr: &actionExpr{
				pos: position{line: 96, col: 19, offset: 3042},
				run: (*parser).callonMultiplicative1,
				expr: &seqExpr{
					pos: position{line: 96, col: 19, offset: 3042},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 96, col: 19, offset: 3042},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 96, col: 25, offset: 3048},
								name: "Unary",
							},
						},
						&labeledExpr{
							pos:   position{line: 96, col: 31, offset: 3054},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 96, col: 36, offset: 3059},
								expr: &actionExpr{
									pos: position{line: 96, col: 38, offset: 3061},
									run: (*parser).callonMultiplicative7,
									expr: &seqExpr{
										pos: position{line: 96, col: 38, offset: 3061},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 96, col: 38, offset: 3061},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 96, col: 40, offset: 3063},
												label: "op",
												expr: &ruleRefExpr{
													pos:  position{line: 96, col: 43, offset: 3066},
													name: "MulOp",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 96, col: 49, offset: 3072},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 96, col: 51, offset: 3074},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 96, col: 53, offset: 3076},
													name: "Unary",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MulOp",
			pos:  position{line: 100, col: 1, offset: 3181},
			expr: &actionExpr{
				pos: position{line: 100, col: 10, offset: 3190},
				run: (*parser).callonMulOp1,
				expr: &labeledExpr{
					pos:   position{line: 100, col: 10, offset: 3190},
					label: "op",
					expr: &choiceExpr{
						pos: position{line: 100, col: 15, offset: 3195},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 100, col: 15, offset: 3195},
								val:        "*",
								ignoreCase: false,
								want:       "\"*\"",
							},
							&litMatcher{
								pos:        position{line: 100, col: 21, offset: 3201},
								val:        "/",
								ignoreCase: false,
								want:       "\"/\"",
							},
						},
					},
				},
			},
		},
		{
			name: "Unary",
			pos:  position{line: 104, col: 1, offset: 3243},
			expr: &actionExpr{
				pos: position{line: 104, col: 10, offset: 3252},
				run: (*parser).callonUnary1,
				expr: &seqExpr{
					pos: position{line: 104, col: 10, offset: 3252},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 104, col: 10, offset: 3252},
							label: "op",
							expr: &zeroOrOneExpr{
								pos: position{line: 104, col: 13, offset: 3255},
								expr: &ruleRefExpr{
									pos:  position{line: 104, col: 13, offset: 3255},
									name: "UnaryOp",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 104, col: 22, offset: 3264},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 104, col: 24, offset: 3266},
							label: "primary",
							expr: &ruleRefExpr{
								pos:  position{line: 104, col: 32, offset: 3274},
								name: "Primary",
							},
						},
					},
				},
			},
		},
		{
			name: "UnaryOp",
			pos:  position{line: 108, col: 1, offset: 3327},
			expr: &actionExpr{
				pos: position{line: 108, col: 12, offset: 3338},
				run: (*parser).callonUnaryOp1,
				expr: &seqExpr{
					pos: position{line: 108, col: 12, offset: 3338},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 108, col: 12, offset: 3338},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 108, col: 17, offset: 3343},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 108, col: 17, offset: 3343},
										val:        "not",
										ignoreCase: true,
										want:       "\"NOT\"i",
									},
									&litMatcher{
										pos:        position{line: 108, col: 26, offset: 3352},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 108, col: 32, offset: 3358},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Primary",
			pos:  position{line: 116, col: 1, offset: 3580},
			expr: &choiceExpr{
				pos: position{line: 116, col: 12, offset: 3591},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 116, col: 12, offset: 3591},
						name: "Literal",
					},
					&ruleRefExpr{
						pos:  position{line: 116, col: 22, offset: 3601},
						name: "FunctionCall",
					},
					&ruleRefExpr{
						pos:  position{line: 116, col: 37, offset: 3616},
						name: "ColumnRef",
					},
					&ruleRefExpr{
						pos:  position{line: 116, col: 49, offset: 3628},
						name: "ParenExpr",
					},
				},
			},
		},
		{
			name: "ParenExpr",
			pos:  position{line: 118, col: 1, offset: 3639},
			expr: &actionExpr{
				pos: position{line: 118, col: 14, offset: 3652},
				run: (*parser).callonParenExpr1,
				expr: &seqExpr{
					pos: position{line: 118, col: 14, offset: 3652},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 118, col: 14, offset: 3652},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 18, offset: 3656},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 118, col: 20, offset: 3658},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 118, col: 25, offset: 3663},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 30, offset: 3668},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 118, col: 32, offset: 3670},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 122, col: 1, offset: 3700},
			expr: &choiceExpr{
				pos: position{line: 122, col: 12, offset: 3711},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 122, col: 12, offset: 3711},
						name: "BoolLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 122, col: 26, offset: 3725},
						name: "StringLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 122, col: 42, offset: 3741},
						name: "IntLiteral",
					},
				},
			},
		},
		{
			name: "IntLiteral",
			pos:  position{line: 124, col: 1, offset: 3753},
			expr: &actionExpr{
				pos: position{line: 124, col: 15, offset: 3767},
				run: (*parser).callonIntLiteral1,
				expr: &oneOrMoreExpr{
					pos: position{line: 124, col: 15, offset: 3767},
					expr: &charClassMatcher{
						pos:        position{line: 124, col: 15, offset: 3767},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "StringLiteral",
			pos:  position{line: 128, col: 1, offset: 3827},
			expr: &actionExpr{
				pos: position{line: 128, col: 18, offset: 3844},
				run: (*parser).callonStringLiteral1,
				expr: &seqExpr{
					pos: position{line: 128, col: 18, offset: 3844},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 128, col: 18, offset: 3844},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&labeledExpr{
							pos:   position{line: 128, col: 23, offset: 3849},
							label: "content",
							expr: &ruleRefExpr{
								pos:  position{line: 128, col: 31, offset: 3857},
								name: "StringContent",
							},
						},
						&litMatcher{
							pos:        position{line: 128, col: 45, offset: 3871},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "StringContent",
			pos:  position{line: 132, col: 1, offset: 3925},
			expr: &actionExpr{
				pos: position{line: 132, col: 18, offset: 3942},
				run: (*parser).callonStringContent1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 132, col: 18, offset: 3942},
					expr: &choiceExpr{
						pos: position{line: 132, col: 20, offset: 3944},
						alternatives: []any{
							&seqExpr{
								pos: position{line: 132, col: 20, offset: 3944},
								exprs: []any{
									&notExpr{
										pos: position{line: 132, col: 20, offset: 3944},
										expr: &litMatcher{
											pos:        position{line: 132, col: 21, offset: 3945},
											val:        "'",
											ignoreCase: false,
											want:       "\"'\"",
										},
									},
									&anyMatcher{
										line: 132, col: 26, offset: 3950,
									},
								},
							},
							&litMatcher{
								pos:        position{line: 132, col: 30, offset: 3954},
								val:        "''",
								ignoreCase: false,
								want:       "\"''\"",
							},
						},
					},
				},
			},
		},
		{
			name: "BoolLiteral",
			pos:  position{line: 136, col: 1, offset: 3998},
			expr: &actionExpr{
				pos: position{line: 136, col: 16, offset: 4013},
				run: (*parser).callonBoolLiteral1,
				expr: &choiceExpr{
					pos: position{line: 136, col: 18, offset: 4015},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 136, col: 18, offset: 4015},
							val:        "true",
							ignoreCase: true,
							want:       "\"TRUE\"i",
						},
						&litMatcher{
							pos:        position{line: 136, col: 28, offset: 4025},
							val:        "false",
							ignoreCase: true,
							want:       "\"FALSE\"i",
						},
					},
				},
			},
		},
		{
			name: "FunctionCall",
			pos:  position{line: 140, col: 1, offset: 4090},
			expr: &actionExpr{
				pos: position{line: 140, col: 17, offset: 4106},
				run: (*parser).callonFunctionCall1,
				expr: &seqExpr{
					pos: position{line: 140, col: 17, offset: 4106},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 140, col: 17, offset: 4106},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 140, col: 22, offset: 4111},
								name: "FunctionName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 140, col: 35, offset: 4124},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 140, col: 37, offset: 4126},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 140, col: 41, offset: 4130},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 140, col: 43, offset: 4132},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 140, col: 48, offset: 4137},
								expr: &ruleRefExpr{
									pos:  position{line: 140, col: 48, offset: 4137},
									name: "FunctionArgs",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 140, col: 62, offset: 4151},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 140, col: 64, offset: 4153},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "FunctionName",
			pos:  position{line: 144, col: 1, offset: 4204},
			expr: &actionExpr{
				pos: position{line: 144, col: 17, offset: 4220},
				run: (*parser).callonFunctionName1,
				expr: &choiceExpr{
					pos: position{line: 144, col: 19, offset: 4222},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 144, col: 19, offset: 4222},
							val:        "strlen",
							ignoreCase: true,
							want:       "\"STRLEN\"i",
						},
						&litMatcher{
							pos:        position{line: 144, col: 31, offset: 4234},
							val:        "concat",
							ignoreCase: true,
							want:       "\"CONCAT\"i",
						},
						&litMatcher{
							pos:        position{line: 144, col: 43, offset: 4246},
							val:        "upper",
							ignoreCase: true,
							want:       "\"UPPER\"i",
						},
						&litMatcher{
							pos:        position{line: 144, col: 54, offset: 4257},
							val:        "lower",
							ignoreCase: true,
							want:       "\"LOWER\"i",
						},
					},
				},
			},
		},
		{
			name: "FunctionArgs",
			pos:  position{line: 148, col: 1, offset: 4304},
			expr: &actionExpr{
				pos: position{line: 148, col: 17, offset: 4320},
				run: (*parser).callonFunctionArgs1,
				expr: &seqExpr{
					pos: position{line: 148, col: 17, offset: 4320},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 148, col: 17, offset: 4320},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 148, col: 23, offset: 4326},
								name: "Expr",
							},
						},
						&labeledExpr{
							pos:   position{line: 148, col: 28, offset: 4331},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 148, col: 33, offset: 4336},
								expr: &actionExpr{
									pos: position{line: 148, col: 35, offset: 4338},
									run: (*parser).callonFunctionArgs7,
									expr: &seqExpr{
										pos: position{line: 148, col: 35, offset: 4338},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 148, col: 35, offset: 4338},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 148, col: 37, offset: 4340},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 148, col: 41, offset: 4344},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 148, col: 43, offset: 4346},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 148, col: 45, offset: 4348},
													name: "Expr",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ColumnRef",
			pos:  position{line: 152, col: 1, offset: 4422},
			expr: &actionExpr{
				pos: position{line: 152, col: 14, offset: 4435},
				run: (*parser).callonColumnRef1,
				expr: &seqExpr{
					pos: position{line: 152, col: 14, offset: 4435},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 152, col: 14, offset: 4435},
							label: "table",
							expr: &zeroOrOneExpr{
								pos: position{line: 152, col: 20, offset: 4441},
								expr: &actionExpr{
									pos: position{line: 152, col: 22, offset: 4443},
									run: (*parser).callonColumnRef5,
									expr: &seqExpr{
										pos: position{line: 152, col: 22, offset: 4443},
										exprs: []any{
											&labeledExpr{
												pos:   position{line: 152, col: 22, offset: 4443},
												label: "name",
												expr: &ruleRefExpr{
													pos:  position{line: 152, col: 27, offset: 4448},
													name: "Identifier",
												},
											},
											&litMatcher{
												pos:        position{line: 152, col: 38, offset: 4459},
												val:        ".",
												ignoreCase: false,
												want:       "\".\"",
											},
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 152, col: 66, offset: 4487},
							label: "column",
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 73, offset: 4494},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 160, col: 1, offset: 4737},
			expr: &actionExpr{
				pos: position{line: 160, col: 15, offset: 4751},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 160, col: 15, offset: 4751},
					exprs: []any{
						&notExpr{
							pos: position{line: 160, col: 15, offset: 4751},
							expr: &ruleRefExpr{
								pos:  position{line: 160, col: 16, offset: 4752},
								name: "ReservedWord",
							},
						},
						&charClassMatcher{
							pos:        position{line: 160, col: 29, offset: 4765},
							val:        "[a-zA-Z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 160, col: 39, offset: 4775},
							expr: &charClassMatcher{
								pos:        position{line: 160, col: 39, offset: 4775},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "ReservedWord",
			pos:  position{line: 164, col: 1, offset: 4825},
			expr: &seqExpr{
				pos: position{line: 164, col: 17, offset: 4841},
				exprs: []any{
					&choiceExpr{
						pos: position{line: 164, col: 19, offset: 4843},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 164, col: 19, offset: 4843},
								val:        "select",
								ignoreCase: true,
								want:       "\"SELECT\"i",
							},
							&litMatcher{
								pos:        position{line: 164, col: 31, offset: 4855},
								val:        "from",
								ignoreCase: true,
								want:       "\"FROM\"i",
							},
							&litMatcher{
								pos:        position{line: 164, col: 41, offset: 4865},
								val:        "where",
								ignoreCase: true,
								want:       "\"WHERE\"i",
							},
							&litMatcher{
								pos:        position{line: 164, col: 52, offset: 4876},
								val:        "order",
								ignoreCase: true,
								want:       "\"ORDER\"i",
							},
							&litMatcher{
								pos:        position{line: 164, col: 63, offset: 4887},
								val:        "by",
								ignoreCase: true,
								want:       "\"BY\"i",
							},
							&litMatcher{
								pos:        position{line: 164, col: 71, offset: 4895},
								val:        "asc",
								ignoreCase: true,
								want:       "\"ASC\"i",
							},
							&litMatcher{
								pos:        position{line: 164, col: 80, offset: 4904},
								val:        "desc",
								ignoreCase: true,
								want:       "\"DESC\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 18, offset: 4932},
								val:        "limit",
								ignoreCase: true,
								want:       "\"LIMIT\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 29, offset: 4943},
								val:        "and",
								ignoreCase: true,
								want:       "\"AND\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 38, offset: 4952},
								val:        "or",
								ignoreCase: true,
								want:       "\"OR\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 46, offset: 4960},
								val:        "not",
								ignoreCase: true,
								want:       "\"NOT\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 55, offset: 4969},
								val:        "true",
								ignoreCase: true,
								want:       "\"TRUE\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 65, offset: 4979},
								val:        "false",
								ignoreCase: true,
								want:       "\"FALSE\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 18, offset: 5007},
								val:        "strlen",
								ignoreCase: true,
								want:       "\"STRLEN\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 30, offset: 5019},
								val:        "concat",
								ignoreCase: true,
								want:       "\"CONCAT\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 42, offset: 5031},
								val:        "upper",
								ignoreCase: true,
								want:       "\"UPPER\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 53, offset: 5042},
								val:        "lower",
								ignoreCase: true,
								want:       "\"LOWER\"i",
							},
						},
					},
					&notExpr{
						pos: position{line: 166, col: 64, offset: 5053},
						expr: &charClassMatcher{
							pos:        position{line: 166, col: 65, offset: 5054},
							val:        "[a-zA-Z0-9_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 168, col: 1, offset: 5068},
			expr: &actionExpr{
				pos: position{line: 168, col: 12, offset: 5079},
				run: (*parser).callonInteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 168, col: 12, offset: 5079},
					expr: &charClassMatcher{
						pos:        position{line: 168, col: 12, offset: 5079},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 172, col: 1, offset: 5132},
			expr: &zeroOrMoreExpr{
				pos: position{line: 172, col: 19, offset: 5150},
				expr: &charClassMatcher{
					pos:        position{line: 172, col: 19, offset: 5150},
					val:        "[ \\t\\n\\r]",
					chars:      []rune{' ', '\t', '\n', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 174, col: 1, offset: 5162},
			expr: &notExpr{
				pos: position{line: 174, col: 8, offset: 5169},
				expr: &anyMatcher{
					line: 174, col: 9, offset: 5170,
				},
			},
		},
	},
}

func (c *current) onQuery1(columns, from, where, orderBy, limit any) (any, error) {
	return buildQuery(columns, from, where, orderBy, limit)
}

func (p *parser) callonQuery1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuery1(stack["columns"], stack["from"], stack["where"], stack["orderBy"], stack["limit"])
}

func (c *current) onColumnList7(e any) (any, error) {
	return e, nil
}

func (p *parser) callonColumnList7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumnList7(stack["e"])
}

func (c *current) onColumnList1(first, rest any) (any, error) {
	return buildColumnList(first, rest), nil
}

func (p *parser) callonColumnList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumnList1(stack["first"], stack["rest"])
}

func (c *current) onFromClause10(name any) (any, error) {
	return name, nil
}

func (p *parser) callonFromClause10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFromClause10(stack["name"])
}

func (c *current) onFromClause1(first, rest any) (any, error) {
	return buildFromClause(first, rest), nil
}

func (p *parser) callonFromClause1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFromClause1(stack["first"], stack["rest"])
}

func (c *current) onWhereClause1(expr any) (any, error) {
	return expr, nil
}

func (p *parser) callonWhereClause1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWhereClause1(stack["expr"])
}

func (c *current) onOrderByClause12(o any) (any, error) {
	return o, nil
}

func (p *parser) callonOrderByClause12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrderByClause12(stack["o"])
}

func (c *current) onOrderByClause1(first, rest any) (any, error) {
	return buildOrderByList(first, rest), nil
}

func (p *parser) callonOrderByClause1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrderByClause1(stack["first"], stack["rest"])
}

func (c *current) onOrderByItem7(d any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonOrderByItem7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrderByItem7(stack["d"])
}

func (c *current) onOrderByItem1(idx, dir any) (any, error) {
	return buildOrderByItem(idx, dir), nil
}

func (p *parser) callonOrderByItem1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrderByItem1(stack["idx"], stack["dir"])
}

func (c *current) onLimitClause1(n any) (any, error) {
	return buildLimitClause(n), nil
}

func (p *parser) callonLimitClause1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLimitClause1(stack["n"])
}

func (c *current) onOrExpr7(e any) (any, error) {
	return e, nil
}

func (p *parser) callonOrExpr7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpr7(stack["e"])
}

func (c *current) onOrExpr1(first, rest any) (any, error) {
	return buildBinaryChain(first, rest, "OR"), nil
}

func (p *parser) callonOrExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpr1(stack["first"], stack["rest"])
}

func (c *current) onAndExpr7(e any) (any, error) {
	return e, nil
}

func (p *parser) callonAndExpr7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpr7(stack["e"])
}

func (c *current) onAndExpr1(first, rest any) (any, error) {
	return buildBinaryChain(first, rest, "AND"), nil
}

func (p *parser) callonAndExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpr1(stack["first"], stack["rest"])
}

func (c *current) onComparison1(left, op, right any) (any, error) {
	return buildComparison(left, op, right), nil
}

func (p *parser) callonComparison1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparison1(stack["left"], stack["op"], stack["right"])
}

func (c *current) onCompOp1(op any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCompOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCompOp1(stack["op"])
}

func (c *current) onAdditive7(op, e any) (any, error) {
	return []interface{}{op, e}, nil
}

func (p *parser) callonAdditive7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditive7(stack["op"], stack["e"])
}

func (c *current) onAdditive1(first, rest any) (any, error) {
	return buildAdditiveChain(first, rest), nil
}

func (p *parser) callonAdditive1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditive1(stack["first"], stack["rest"])
}

func (c *current) onAddOp1(op any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonAddOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddOp1(stack["op"])
}

func (c *current) onMultiplicative7(op, e any) (any, error) {
	return []interface{}{op, e}, nil
}

func (p *parser) callonMultiplicative7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicative7(stack["op"], stack["e"])
}

func (c *current) onMultiplicative1(first, rest any) (any, error) {
	return buildMultiplicativeChain(first, rest), nil
}

func (p *parser) callonMultiplicative1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicative1(stack["first"], stack["rest"])
}

func (c *current) onMulOp1(op any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonMulOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulOp1(stack["op"])
}

func (c *current) onUnary1(op, primary any) (any, error) {
	return buildUnary(op, primary), nil
}

func (p *parser) callonUnary1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnary1(stack["op"], stack["primary"])
}

func (c *current) onUnaryOp1(op any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUnaryOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnaryOp1(stack["op"])
}

func (c *current) onParenExpr1(expr any) (any, error) {
	return expr, nil
}

func (p *parser) callonParenExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenExpr1(stack["expr"])
}

func (c *current) onIntLiteral1() (any, error) {
	return buildIntLiteral(string(c.text)), nil
}

func (p *parser) callonIntLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntLiteral1()
}

func (c *current) onStringLiteral1(content any) (any, error) {
	return buildStringLiteral(content), nil
}

func (p *parser) callonStringLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral1(stack["content"])
}

func (c *current) onStringContent1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonStringContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringContent1()
}

func (c *current) onBoolLiteral1() (any, error) {
	return buildBoolLiteral(string(c.text)), nil
}

func (p *parser) callonBoolLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolLiteral1()
}

func (c *current) onFunctionCall1(name, args any) (any, error) {
	return buildFunction(name, args), nil
}

func (p *parser) callonFunctionCall1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionCall1(stack["name"], stack["args"])
}

func (c *current) onFunctionName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonFunctionName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionName1()
}

func (c *current) onFunctionArgs7(e any) (any, error) {
	return e, nil
}

func (p *parser) callonFunctionArgs7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionArgs7(stack["e"])
}

func (c *current) onFunctionArgs1(first, rest any) (any, error) {
	return buildArgsList(first, rest), nil
}

func (p *parser) callonFunctionArgs1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionArgs1(stack["first"], stack["rest"])
}

func (c *current) onColumnRef5(name any) (any, error) {
	return name, nil
}

func (p *parser) callonColumnRef5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumnRef5(stack["name"])
}

func (c *current) onColumnRef1(table, column any) (any, error) {
	return buildColumnRef(table, column), nil
}

func (p *parser) callonColumnRef1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumnRef1(stack["table"], stack["column"])
}

func (c *current) onIdentifier1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onInteger1() (any, error) {
	return parseInt(string(c.text)), nil
}

func (p *parser) callonInteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
