/*
 * Generated by ChatGPT
 *
 * Modified by Dawid Pawlik
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

#define CRC64_POLY 0x42F0E1EBA9EA3693ULL

static uint64_t crc64_table[256];

void crc64_init();
uint64_t crc64_update(uint64_t crc, const unsigned char* buf, size_t len);
void print_crc64(uint64_t crc);
