/*
 * Generated by ChatGPT
 *
 * Modified by Dawid Pawlik
 */

#include "crc64.h"

#include <stdio.h>

void crc64_init() {
    for (int i = 0; i < 256; i++) {
        uint64_t crc = (uint64_t)i << 56;
        for (int j = 0; j < 8; j++) {
            if (crc & 0x8000000000000000ULL)
                crc = (crc << 1) ^ CRC64_POLY;
            else
                crc <<= 1;
        }
        crc64_table[i] = crc;
    }
}

uint64_t crc64_update(uint64_t crc, const unsigned char* buf, size_t len) {
    while (len--) {
        uint8_t index = (uint8_t)((crc >> 56) ^ *buf++);
        crc = crc64_table[index] ^ (crc << 8);
    }
    return crc;
}

void print_crc64(uint64_t crc) {
    printf("CRC64: %016llx\n", (unsigned long long)crc);
}
